//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MoneyRecord.Resources.Strings {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MoneyRecord.Resources.Strings.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Account *.
        /// </summary>
        internal static string Account {
            get {
                return ResourceManager.GetString("Account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Account Balances.
        /// </summary>
        internal static string AccountBalances {
            get {
                return ResourceManager.GetString("AccountBalances", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Account Name.
        /// </summary>
        internal static string AccountName {
            get {
                return ResourceManager.GetString("AccountName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a e.g., Bank Account, Cash, Credit Card.
        /// </summary>
        internal static string AccountNamePlaceholder {
            get {
                return ResourceManager.GetString("AccountNamePlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Accounts.
        /// </summary>
        internal static string Accounts {
            get {
                return ResourceManager.GetString("Accounts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ➕ Add Account.
        /// </summary>
        internal static string AddAccountButton {
            get {
                return ResourceManager.GetString("AddAccountButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Add Category.
        /// </summary>
        internal static string AddCategoryButton {
            get {
                return ResourceManager.GetString("AddCategoryButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Add Expense.
        /// </summary>
        internal static string AddExpense {
            get {
                return ResourceManager.GetString("AddExpense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Add some expenses to see your spending breakdown.
        /// </summary>
        internal static string AddExpensesToStart {
            get {
                return ResourceManager.GetString("AddExpensesToStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Add some expense transactions to see your spending analysis.
        /// </summary>
        internal static string AddExpenseTransactionsToSee {
            get {
                return ResourceManager.GetString("AddExpenseTransactionsToSee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Add Income.
        /// </summary>
        internal static string AddIncome {
            get {
                return ResourceManager.GetString("AddIncome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Add some income to see your earnings breakdown.
        /// </summary>
        internal static string AddIncomeToStart {
            get {
                return ResourceManager.GetString("AddIncomeToStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Add some income transactions to see your earnings analysis.
        /// </summary>
        internal static string AddIncomeTransactionsToSee {
            get {
                return ResourceManager.GetString("AddIncomeTransactionsToSee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Add New Account.
        /// </summary>
        internal static string AddNewAccount {
            get {
                return ResourceManager.GetString("AddNewAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Add New Category.
        /// </summary>
        internal static string AddNewCategory {
            get {
                return ResourceManager.GetString("AddNewCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Add Transaction.
        /// </summary>
        internal static string AddTransaction {
            get {
                return ResourceManager.GetString("AddTransaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a All expense categories by percentage.
        /// </summary>
        internal static string AllExpenseCategoriesByPercentage {
            get {
                return ResourceManager.GetString("AllExpenseCategoriesByPercentage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a All income categories by percentage.
        /// </summary>
        internal static string AllIncomeCategoriesByPercentage {
            get {
                return ResourceManager.GetString("AllIncomeCategoriesByPercentage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Allow negative balance.
        /// </summary>
        internal static string AllowNegativeBalance {
            get {
                return ResourceManager.GetString("AllowNegativeBalance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Amount *.
        /// </summary>
        internal static string Amount {
            get {
                return ResourceManager.GetString("Amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Money Record.
        /// </summary>
        internal static string AppTitle {
            get {
                return ResourceManager.GetString("AppTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Available: ${0:N2}.
        /// </summary>
        internal static string AvailableBalance {
            get {
                return ResourceManager.GetString("AvailableBalance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ← Back.
        /// </summary>
        internal static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cancel.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ❌ Cancel Edit.
        /// </summary>
        internal static string CancelEdit {
            get {
                return ResourceManager.GetString("CancelEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cannot Delete.
        /// </summary>
        internal static string CannotDelete {
            get {
                return ResourceManager.GetString("CannotDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Categories.
        /// </summary>
        internal static string Categories {
            get {
                return ResourceManager.GetString("Categories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Category *.
        /// </summary>
        internal static string Category {
            get {
                return ResourceManager.GetString("Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 📁 Category Breakdown.
        /// </summary>
        internal static string CategoryBreakdown {
            get {
                return ResourceManager.GetString("CategoryBreakdown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 📋 Category Details.
        /// </summary>
        internal static string CategoryDetails {
            get {
                return ResourceManager.GetString("CategoryDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &apos;{0}&apos; has existing transactions. Select a category to move them to:.
        /// </summary>
        internal static string CategoryHasTransactions {
            get {
                return ResourceManager.GetString("CategoryHasTransactions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Category name.
        /// </summary>
        internal static string CategoryName {
            get {
                return ResourceManager.GetString("CategoryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Confirm.
        /// </summary>
        internal static string Confirm {
            get {
                return ResourceManager.GetString("Confirm", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Custom Period.
        /// </summary>
        internal static string CustomPeriod {
            get {
                return ResourceManager.GetString("CustomPeriod", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Calendar Month.
        /// </summary>
        internal static string CalendarMonth {
            get {
                return ResourceManager.GetString("CalendarMonth", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Calendar Year.
        /// </summary>
        internal static string CalendarYear {
            get {
                return ResourceManager.GetString("CalendarYear", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Date *.
        /// </summary>
        internal static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cash.
        /// </summary>
        internal static string DefaultAccountCash {
            get {
                return ResourceManager.GetString("DefaultAccountCash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Entertainment.
        /// </summary>
        internal static string DefaultCategoryEntertainment {
            get {
                return ResourceManager.GetString("DefaultCategoryEntertainment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Food.
        /// </summary>
        internal static string DefaultCategoryFood {
            get {
                return ResourceManager.GetString("DefaultCategoryFood", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Freelance.
        /// </summary>
        internal static string DefaultCategoryFreelance {
            get {
                return ResourceManager.GetString("DefaultCategoryFreelance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Home.
        /// </summary>
        internal static string DefaultCategoryHome {
            get {
                return ResourceManager.GetString("DefaultCategoryHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Investment.
        /// </summary>
        internal static string DefaultCategoryInvestment {
            get {
                return ResourceManager.GetString("DefaultCategoryInvestment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Other Expense.
        /// </summary>
        internal static string DefaultCategoryOtherExpense {
            get {
                return ResourceManager.GetString("DefaultCategoryOtherExpense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Other Income.
        /// </summary>
        internal static string DefaultCategoryOtherIncome {
            get {
                return ResourceManager.GetString("DefaultCategoryOtherIncome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Salary.
        /// </summary>
        internal static string DefaultCategorySalary {
            get {
                return ResourceManager.GetString("DefaultCategorySalary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Shopping.
        /// </summary>
        internal static string DefaultCategoryShopping {
            get {
                return ResourceManager.GetString("DefaultCategoryShopping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Transportation.
        /// </summary>
        internal static string DefaultCategoryTransportation {
            get {
                return ResourceManager.GetString("DefaultCategoryTransportation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Utilities.
        /// </summary>
        internal static string DefaultCategoryUtilities {
            get {
                return ResourceManager.GetString("DefaultCategoryUtilities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Delete.
        /// </summary>
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Delete Account.
        /// </summary>
        internal static string DeleteAccount {
            get {
                return ResourceManager.GetString("DeleteAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Are you sure you want to delete this account?.
        /// </summary>
        internal static string DeleteAccountConfirm {
            get {
                return ResourceManager.GetString("DeleteAccountConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 🗑️ Delete.
        /// </summary>
        internal static string DeleteButton {
            get {
                return ResourceManager.GetString("DeleteButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Delete Category.
        /// </summary>
        internal static string DeleteCategory {
            get {
                return ResourceManager.GetString("DeleteCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Are you sure you want to delete this category?.
        /// </summary>
        internal static string DeleteCategoryConfirm {
            get {
                return ResourceManager.GetString("DeleteCategoryConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Delete Transaction.
        /// </summary>
        internal static string DeleteTransaction {
            get {
                return ResourceManager.GetString("DeleteTransaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Are you sure you want to delete this transaction?.
        /// </summary>
        internal static string DeleteTransactionConfirm {
            get {
                return ResourceManager.GetString("DeleteTransactionConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Delete Transfer.
        /// </summary>
        internal static string DeleteTransfer {
            get {
                return ResourceManager.GetString("DeleteTransfer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Are you sure you want to delete this transfer?.
        /// </summary>
        internal static string DeleteTransferConfirm {
            get {
                return ResourceManager.GetString("DeleteTransferConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Description *.
        /// </summary>
        internal static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Edit.
        /// </summary>
        internal static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Edit Account.
        /// </summary>
        internal static string EditAccount {
            get {
                return ResourceManager.GetString("EditAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ✏️ Edit.
        /// </summary>
        internal static string EditButton {
            get {
                return ResourceManager.GetString("EditButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Edit Category.
        /// </summary>
        internal static string EditCategory {
            get {
                return ResourceManager.GetString("EditCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Edit Expense.
        /// </summary>
        internal static string EditExpense {
            get {
                return ResourceManager.GetString("EditExpense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Edit Income.
        /// </summary>
        internal static string EditIncome {
            get {
                return ResourceManager.GetString("EditIncome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Edit Transfer.
        /// </summary>
        internal static string EditTransfer {
            get {
                return ResourceManager.GetString("EditTransfer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enter description.
        /// </summary>
        internal static string EnterDescription {
            get {
                return ResourceManager.GetString("EnterDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 💸 Expense.
        /// </summary>
        internal static string Expense {
            get {
                return ResourceManager.GetString("Expense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 📊 Expense Analysis.
        /// </summary>
        internal static string ExpenseAnalysis {
            get {
                return ResourceManager.GetString("ExpenseAnalysis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Expense Categories.
        /// </summary>
        internal static string ExpenseCategories {
            get {
                return ResourceManager.GetString("ExpenseCategories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 🔥 Expense Heatmap.
        /// </summary>
        internal static string ExpenseHeatmap {
            get {
                return ResourceManager.GetString("ExpenseHeatmap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Expense Report.
        /// </summary>
        internal static string ExpenseReport {
            get {
                return ResourceManager.GetString("ExpenseReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Expenses.
        /// </summary>
        internal static string Expenses {
            get {
                return ResourceManager.GetString("Expenses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a From:.
        /// </summary>
        internal static string From {
            get {
                return ResourceManager.GetString("From", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a From Account *.
        /// </summary>
        internal static string FromAccount {
            get {
                return ResourceManager.GetString("FromAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a From:.
        /// </summary>
        internal static string FromLabel {
            get {
                return ResourceManager.GetString("FromLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 🏦 By Account.
        /// </summary>
        internal static string GroupByAccount {
            get {
                return ResourceManager.GetString("GroupByAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 📂 By Category.
        /// </summary>
        internal static string GroupByCategory {
            get {
                return ResourceManager.GetString("GroupByCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 📂 Grouped.
        /// </summary>
        internal static string Grouped {
            get {
                return ResourceManager.GetString("Grouped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a High.
        /// </summary>
        internal static string High {
            get {
                return ResourceManager.GetString("High", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Home.
        /// </summary>
        internal static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Identify your most used expense categories.
        /// </summary>
        internal static string IdentifyExpenseCategories {
            get {
                return ResourceManager.GetString("IdentifyExpenseCategories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Identify your most used income categories.
        /// </summary>
        internal static string IdentifyIncomeCategories {
            get {
                return ResourceManager.GetString("IdentifyIncomeCategories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 💰 Income.
        /// </summary>
        internal static string Income {
            get {
                return ResourceManager.GetString("Income", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 💵 Income Analysis.
        /// </summary>
        internal static string IncomeAnalysis {
            get {
                return ResourceManager.GetString("IncomeAnalysis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Income Categories.
        /// </summary>
        internal static string IncomeCategories {
            get {
                return ResourceManager.GetString("IncomeCategories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 🔥 Income Heatmap.
        /// </summary>
        internal static string IncomeHeatmap {
            get {
                return ResourceManager.GetString("IncomeHeatmap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Income Report.
        /// </summary>
        internal static string IncomeReport {
            get {
                return ResourceManager.GetString("IncomeReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Incomes.
        /// </summary>
        internal static string Incomes {
            get {
                return ResourceManager.GetString("Incomes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Initial Balance.
        /// </summary>
        internal static string InitialBalance {
            get {
                return ResourceManager.GetString("InitialBalance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a This expense would result in a negative balance. The account &apos;{0}&apos; does not allow negative balance..
        /// </summary>
        internal static string InsufficientAccountBalance {
            get {
                return ResourceManager.GetString("InsufficientAccountBalance", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Negative initial balance is not allowed. Enable 'Allow negative balance' to use a negative value..
        /// </summary>
        internal static string NegativeBalanceNotAllowed {
            get {
                return ResourceManager.GetString("NegativeBalanceNotAllowed", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Insufficient funds in source account.
        /// </summary>
        internal static string InsufficientFunds {
            get {
                return ResourceManager.GetString("InsufficientFunds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a This is the last category of this type. You cannot delete it while it has transactions. Please create another category first..
        /// </summary>
        internal static string LastCategoryCannotDelete {
            get {
                return ResourceManager.GetString("LastCategoryCannotDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Last Month.
        /// </summary>
        internal static string LastMonth {
            get {
                return ResourceManager.GetString("LastMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Last Week.
        /// </summary>
        internal static string LastWeek {
            get {
                return ResourceManager.GetString("LastWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Last Year.
        /// </summary>
        internal static string LastYear {
            get {
                return ResourceManager.GetString("LastYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 📄 List View.
        /// </summary>
        internal static string ListView {
            get {
                return ResourceManager.GetString("ListView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Low.
        /// </summary>
        internal static string Low {
            get {
                return ResourceManager.GetString("Low", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Manage Accounts.
        /// </summary>
        internal static string ManageAccounts {
            get {
                return ResourceManager.GetString("ManageAccounts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Manage Categories.
        /// </summary>
        internal static string ManageCategories {
            get {
                return ResourceManager.GetString("ManageCategories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Manage Expense Categories.
        /// </summary>
        internal static string ManageExpenseCategories {
            get {
                return ResourceManager.GetString("ManageExpenseCategories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Manage Income Categories.
        /// </summary>
        internal static string ManageIncomeCategories {
            get {
                return ResourceManager.GetString("ManageIncomeCategories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Medium.
        /// </summary>
        internal static string Medium {
            get {
                return ResourceManager.GetString("Medium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 🔄 New Transfer.
        /// </summary>
        internal static string NewTransfer {
            get {
                return ResourceManager.GetString("NewTransfer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No.
        /// </summary>
        internal static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No accounts yet. Add your first account above..
        /// </summary>
        internal static string NoAccounts {
            get {
                return ResourceManager.GetString("NoAccounts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No categories yet. Add your first category above..
        /// </summary>
        internal static string NoCategories {
            get {
                return ResourceManager.GetString("NoCategories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No categories yet.
        /// </summary>
        internal static string NoCategoriesYet {
            get {
                return ResourceManager.GetString("NoCategoriesYet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No expense data for this period.
        /// </summary>
        internal static string NoExpenseData {
            get {
                return ResourceManager.GetString("NoExpenseData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No expense data found.
        /// </summary>
        internal static string NoExpenseDataFound {
            get {
                return ResourceManager.GetString("NoExpenseDataFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No income data for this period.
        /// </summary>
        internal static string NoIncomeData {
            get {
                return ResourceManager.GetString("NoIncomeData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No income data found.
        /// </summary>
        internal static string NoIncomeDataFound {
            get {
                return ResourceManager.GetString("NoIncomeDataFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a There are no transactions to show.
        /// </summary>
        internal static string NoTransactions {
            get {
                return ResourceManager.GetString("NoTransactions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No transfers yet.
        /// </summary>
        internal static string NoTransfers {
            get {
                return ResourceManager.GetString("NoTransfers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a OK.
        /// </summary>
        internal static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Please enter an account name.
        /// </summary>
        internal static string PleaseEnterAccountName {
            get {
                return ResourceManager.GetString("PleaseEnterAccountName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Please enter a category name.
        /// </summary>
        internal static string PleaseEnterCategoryName {
            get {
                return ResourceManager.GetString("PleaseEnterCategoryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Please enter a description.
        /// </summary>
        internal static string PleaseEnterDescription {
            get {
                return ResourceManager.GetString("PleaseEnterDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Please enter a valid amount.
        /// </summary>
        internal static string PleaseEnterValidAmount {
            get {
                return ResourceManager.GetString("PleaseEnterValidAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Please select an account.
        /// </summary>
        internal static string PleaseSelectAccount {
            get {
                return ResourceManager.GetString("PleaseSelectAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Please select a category.
        /// </summary>
        internal static string PleaseSelectCategory {
            get {
                return ResourceManager.GetString("PleaseSelectCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Please select a destination account.
        /// </summary>
        internal static string PleaseSelectDestinationAccount {
            get {
                return ResourceManager.GetString("PleaseSelectDestinationAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Please select a source account.
        /// </summary>
        internal static string PleaseSelectSourceAccount {
            get {
                return ResourceManager.GetString("PleaseSelectSourceAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a * Required fields.
        /// </summary>
        internal static string RequiredFields {
            get {
                return ResourceManager.GetString("RequiredFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Save.
        /// </summary>
        internal static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Select Account.
        /// </summary>
        internal static string SelectAccount {
            get {
                return ResourceManager.GetString("SelectAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Select Category.
        /// </summary>
        internal static string SelectCategory {
            get {
                return ResourceManager.GetString("SelectCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Select Destination Account.
        /// </summary>
        internal static string SelectDestinationAccount {
            get {
                return ResourceManager.GetString("SelectDestinationAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Select Icon.
        /// </summary>
        internal static string SelectIcon {
            get {
                return ResourceManager.GetString("SelectIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Select Period.
        /// </summary>
        internal static string SelectPeriod {
            get {
                return ResourceManager.GetString("SelectPeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Select Source Account.
        /// </summary>
        internal static string SelectSourceAccount {
            get {
                return ResourceManager.GetString("SelectSourceAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sort.
        /// </summary>
        internal static string Sort {
            get {
                return ResourceManager.GetString("Sort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ↓ Newest First.
        /// </summary>
        internal static string SortNewestFirst {
            get {
                return ResourceManager.GetString("SortNewestFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ↑ Oldest First.
        /// </summary>
        internal static string SortOldestFirst {
            get {
                return ResourceManager.GetString("SortOldestFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Source and destination accounts must be different.
        /// </summary>
        internal static string SourceDestinationMustBeDifferent {
            get {
                return ResourceManager.GetString("SourceDestinationMustBeDifferent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Start tracking your finances by adding your first transaction.
        /// </summary>
        internal static string StartTracking {
            get {
                return ResourceManager.GetString("StartTracking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Summary.
        /// </summary>
        internal static string Summary {
            get {
                return ResourceManager.GetString("Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a • Tap for details.
        /// </summary>
        internal static string TapForDetails {
            get {
                return ResourceManager.GetString("TapForDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a To:.
        /// </summary>
        internal static string To {
            get {
                return ResourceManager.GetString("To", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a To Account *.
        /// </summary>
        internal static string ToAccount {
            get {
                return ResourceManager.GetString("ToAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Today.
        /// </summary>
        internal static string Today {
            get {
                return ResourceManager.GetString("Today", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a To:.
        /// </summary>
        internal static string ToLabel {
            get {
                return ResourceManager.GetString("ToLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Total Balance (Tap for details).
        /// </summary>
        internal static string TotalBalance {
            get {
                return ResourceManager.GetString("TotalBalance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Total Expenses.
        /// </summary>
        internal static string TotalExpenses {
            get {
                return ResourceManager.GetString("TotalExpenses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Total Income.
        /// </summary>
        internal static string TotalIncome {
            get {
                return ResourceManager.GetString("TotalIncome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Transactions.
        /// </summary>
        internal static string Transactions {
            get {
                return ResourceManager.GetString("Transactions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 🔄 Transfer.
        /// </summary>
        internal static string Transfer {
            get {
                return ResourceManager.GetString("Transfer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Transfer money between your accounts.
        /// </summary>
        internal static string TransferBetweenAccounts {
            get {
                return ResourceManager.GetString("TransferBetweenAccounts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Transfer.
        /// </summary>
        internal static string TransferButton {
            get {
                return ResourceManager.GetString("TransferButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Description.
        /// </summary>
        internal static string TransferDescription {
            get {
                return ResourceManager.GetString("TransferDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Transfer (optional).
        /// </summary>
        internal static string TransferOptional {
            get {
                return ResourceManager.GetString("TransferOptional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Transfers.
        /// </summary>
        internal static string Transfers {
            get {
                return ResourceManager.GetString("Transfers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 📋 Ungrouped.
        /// </summary>
        internal static string Ungrouped {
            get {
                return ResourceManager.GetString("Ungrouped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 💾 Update Account.
        /// </summary>
        internal static string UpdateAccount {
            get {
                return ResourceManager.GetString("UpdateAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 💾 Update Category.
        /// </summary>
        internal static string UpdateCategory {
            get {
                return ResourceManager.GetString("UpdateCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Yes.
        /// </summary>
        internal static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Your Accounts.
        /// </summary>
        internal static string YourAccounts {
            get {
                return ResourceManager.GetString("YourAccounts", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Your Categories.
        /// </summary>
        internal static string YourCategories {
            get {
                return ResourceManager.GetString("YourCategories", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Success.
        /// </summary>
        internal static string Success {
            get {
                return ResourceManager.GetString("Success", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Close.
        /// </summary>
        internal static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Confirm Delete.
        /// </summary>
        internal static string ConfirmDelete {
            get {
                return ResourceManager.GetString("ConfirmDelete", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Yes, Delete.
        /// </summary>
        internal static string YesDelete {
            get {
                return ResourceManager.GetString("YesDelete", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a No accounts found.
        /// </summary>
        internal static string NoAccountsFound {
            get {
                return ResourceManager.GetString("NoAccountsFound", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Balance.
        /// </summary>
        internal static string Balance {
            get {
                return ResourceManager.GetString("Balance", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Last Activity.
        /// </summary>
        internal static string LastActivity {
            get {
                return ResourceManager.GetString("LastActivity", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Failed to load account balances: {0}.
        /// </summary>
        internal static string FailedToLoadAccountBalances {
            get {
                return ResourceManager.GetString("FailedToLoadAccountBalances", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Failed to toggle view: {0}.
        /// </summary>
        internal static string FailedToToggleView {
            get {
                return ResourceManager.GetString("FailedToToggleView", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Failed to load report data: {0}.
        /// </summary>
        internal static string FailedToLoadReportData {
            get {
                return ResourceManager.GetString("FailedToLoadReportData", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a No income details found.
        /// </summary>
        internal static string NoIncomeDetailsFound {
            get {
                return ResourceManager.GetString("NoIncomeDetailsFound", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a No expense details found.
        /// </summary>
        internal static string NoExpenseDetailsFound {
            get {
                return ResourceManager.GetString("NoExpenseDetailsFound", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a No description.
        /// </summary>
        internal static string NoDescription {
            get {
                return ResourceManager.GetString("NoDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Total.
        /// </summary>
        internal static string Total {
            get {
                return ResourceManager.GetString("Total", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a transaction.
        /// </summary>
        internal static string TransactionSingular {
            get {
                return ResourceManager.GetString("TransactionSingular", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a transactions.
        /// </summary>
        internal static string TransactionPlural {
            get {
                return ResourceManager.GetString("TransactionPlural", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Failed to load category details: {0}.
        /// </summary>
        internal static string FailedToLoadCategoryDetails {
            get {
                return ResourceManager.GetString("FailedToLoadCategoryDetails", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Cannot delete the default Cash account.
        /// </summary>
        internal static string CannotDeleteDefaultAccount {
            get {
                return ResourceManager.GetString("CannotDeleteDefaultAccount", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Are you sure you want to delete '{0}'? All transactions in this account will be moved to the Cash account.
        /// </summary>
        internal static string DeleteAccountWithTransactions {
            get {
                return ResourceManager.GetString("DeleteAccountWithTransactions", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Are you sure you want to delete '{0}'?.
        /// </summary>
        internal static string DeleteAccountNoTransactions {
            get {
                return ResourceManager.GetString("DeleteAccountNoTransactions", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Category '{0}' deleted and {1} transaction(s) moved to '{2}'.
        /// </summary>
        internal static string CategoryDeletedAndTransactionsMoved {
            get {
                return ResourceManager.GetString("CategoryDeletedAndTransactionsMoved", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Are you sure you want to delete '{0}'?.
        /// </summary>
        internal static string DeleteCategoryConfirmation {
            get {
                return ResourceManager.GetString("DeleteCategoryConfirmation", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Transfer updated successfully.
        /// </summary>
        internal static string TransferUpdatedSuccessfully {
            get {
                return ResourceManager.GetString("TransferUpdatedSuccessfully", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Failed to save transfer: {0}.
        /// </summary>
        internal static string FailedToSaveTransfer {
            get {
                return ResourceManager.GetString("FailedToSaveTransfer", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Failed to load transfers: {0}.
        /// </summary>
        internal static string FailedToLoadTransfers {
            get {
                return ResourceManager.GetString("FailedToLoadTransfers", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Are you sure you want to delete this transfer?.
        /// </summary>
        internal static string DeleteTransferConfirmMessage {
            get {
                return ResourceManager.GetString("DeleteTransferConfirmMessage", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Transfer deleted successfully.
        /// </summary>
        internal static string TransferDeletedSuccessfully {
            get {
                return ResourceManager.GetString("TransferDeletedSuccessfully", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Failed to delete transfer: {0}.
        /// </summary>
        internal static string FailedToDeleteTransfer {
            get {
                return ResourceManager.GetString("FailedToDeleteTransfer", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Available: ${0:N2}.
        /// </summary>
        internal static string Available {
            get {
                return ResourceManager.GetString("Available", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Budget Mode.
        /// </summary>
        internal static string BudgetMode {
            get {
                return ResourceManager.GetString("BudgetMode", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Add Category to Budget.
        /// </summary>
        internal static string AddCategoryToBudget {
            get {
                return ResourceManager.GetString("AddCategoryToBudget", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Budget Limit.
        /// </summary>
        internal static string BudgetLimit {
            get {
                return ResourceManager.GetString("BudgetLimit", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Add Budget.
        /// </summary>
        internal static string AddBudgetButton {
            get {
                return ResourceManager.GetString("AddBudgetButton", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Your Budgets.
        /// </summary>
        internal static string YourBudgets {
            get {
                return ResourceManager.GetString("YourBudgets", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a No budgets yet.
        /// </summary>
        internal static string NoBudgetsYet {
            get {
                return ResourceManager.GetString("NoBudgetsYet", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Add expense categories to your budget to track spending limits.
        /// </summary>
        internal static string AddBudgetToStart {
            get {
                return ResourceManager.GetString("AddBudgetToStart", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Spent.
        /// </summary>
        internal static string Spent {
            get {
                return ResourceManager.GetString("Spent", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Remaining.
        /// </summary>
        internal static string Remaining {
            get {
                return ResourceManager.GetString("Remaining", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Exceeded.
        /// </summary>
        internal static string Exceeded {
            get {
                return ResourceManager.GetString("Exceeded", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Budgeted.
        /// </summary>
        internal static string TotalBudgeted {
            get {
                return ResourceManager.GetString("TotalBudgeted", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Spent.
        /// </summary>
        internal static string TotalSpent {
            get {
                return ResourceManager.GetString("TotalSpent", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Remaining.
        /// </summary>
        internal static string TotalRemaining {
            get {
                return ResourceManager.GetString("TotalRemaining", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Budget added successfully.
        /// </summary>
        internal static string BudgetAddedSuccessfully {
            get {
                return ResourceManager.GetString("BudgetAddedSuccessfully", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Failed to save budget: {0}.
        /// </summary>
        internal static string FailedToSaveBudget {
            get {
                return ResourceManager.GetString("FailedToSaveBudget", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Are you sure you want to remove '{0}' from your budget?.
        /// </summary>
        internal static string DeleteBudgetConfirmation {
            get {
                return ResourceManager.GetString("DeleteBudgetConfirmation", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Failed to delete budget: {0}.
        /// </summary>
        internal static string FailedToDeleteBudget {
            get {
                return ResourceManager.GetString("FailedToDeleteBudget", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Edit Budget.
        /// </summary>
        internal static string EditBudget {
            get {
                return ResourceManager.GetString("EditBudget", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Enter new budget limit for {0}:.
        /// </summary>
        internal static string EnterNewBudgetLimit {
            get {
                return ResourceManager.GetString("EnterNewBudgetLimit", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Transaction updated successfully.
        /// </summary>
        internal static string TransactionUpdatedSuccessfully {
            get {
                return ResourceManager.GetString("TransactionUpdatedSuccessfully", resourceCulture);
            }
        }
    }
}
